import {PlayerId} from '../common/Types';
import {CardName} from '../common/cards/CardName';
import {Color} from '../common/Color';
import {SerializedCard} from './SerializedCard';
import {SerializedTimer} from '../common/SerializedTimer';
import {GlobalParameter} from '../common/GlobalParameter';
import {DiscordId} from './server/auth/discord';

export interface SerializedPlayer {
  actionsTakenThisGame: number;
  actionsTakenThisRound: number;
  availableActionsThisRound?: number;
  actionsThisGeneration: Array<CardName>;
  autoPass: boolean;
  beginner: boolean;
  canUseHeatAsMegaCredits: boolean;
  canUseTitaniumAsMegacredits: boolean;
  canUsePlantsAsMegaCredits: boolean;
  cardCost: number;
  cardsInHand: Array<CardName>;
  color: Color;
  dealtCorporationCards: Array<CardName>;
  dealtProjectCards: Array<CardName>;
  draftedCards: Array<CardName>;
  draftHand: Array<CardName>,
  energy: number;
  energyProduction: number;
  globalParameterSteps: Partial<Record<GlobalParameter, number>>;
  handicap: number;
  hasIncreasedTerraformRatingThisGeneration: boolean;
  heat: number;
  heatProduction: number;
  id: PlayerId;
  jovianTagCount: number;
  lastCardPlayed?: CardName;
  megaCreditProduction: number;
  megaCredits: number;
  name: string;
  needsToDraft: boolean | undefined;
  oceanBonus: number;
  pendingInitialActions: Array<CardName> | undefined;
  pickedCorporationCard: CardName | undefined;
  plantProduction: number;
  plants: number;
  plantsNeededForGreenery: number;
  plantTagCount: number;
  playedCards: Array<SerializedCard>;
  preservationProgram: boolean;
  removedFromPlayCards: Array<CardName>;
  removingPlayers: Array<PlayerId>;
  scienceTagCount: number;
  standardProjectsThisGeneration: Array<CardName>;
  steel: number;
  steelProduction: number;
  steelValue: number;
  terraformRating: number;
  timer: SerializedTimer;
  titanium: number;
  titaniumProduction: number;
  titaniumValue: number;
  victoryPointsByGeneration: Array<number>;
  user?: DiscordId;
}
