export enum CardRenderItemType {
  TEMPERATURE = 'temperature',
  OXYGEN = 'oxygen',
  OCEANS = 'oceans',
  PLANTS = 'plants',
  TR = 'tr',
  HEAT = 'heat',
  ENERGY = 'energy',
  TITANIUM = 'titanium',
  STEEL = 'steel',
  MEGACREDITS = 'megacredits',
  CARDS = 'cards',
  TAG = 'tag',
  RESOURCE = 'resource',

  CITY = 'city',
  GREENERY = 'greenery',
  PLATE = 'plate',
  TEXT = 'text',
  EMPTY_TILE = 'empty_tile',
  EMPTY_TILE_SPECIAL = 'empty_tile_special',
  MULTIPLIER_WHITE = 'multiplier_white',
  IGNORE_GLOBAL_REQUIREMENTS = 'ignore_global_requirements',
  AWARD = 'award',
  MILESTONE = 'milestone',
  CORPORATION = 'corporation',
  VP = 'vp',
}
