import {AwardName} from '../../common/ma/AwardName';
import {MilestoneName} from '../../common/ma/MilestoneName';

// Higher synergies represent similar milestones or awards. For instance, Terraformer rewards for high TR
// and the Benefactor award is given to the player with the highest TR. Their synergy weight is 9, very high.

const synergiesData: Array<
  [MilestoneName | AwardName, MilestoneName | AwardName, number]
> = [
  ['Terraformer', 'Benefactor', 9],
  ['Gardener', 'Cultivator', 9],
  ['Builder', 'Contractor', 9],
  ['Estate Dealer', 'Cultivator', 8],
  ['Landlord', 'Cultivator', 8],
  ['Landlord', 'Desert Settler', 7],
  ['Landlord', 'Estate Dealer', 7],
  ['Desert Settler', 'Cultivator', 7],
  ['Miner', 'Industrialist', 7],
  ['Energizer', 'Industrialist', 6],
  ['Gardener', 'Landlord', 6],
  ['Mayor', 'Landlord', 6],
  ['Mayor', 'Cultivator', 6],
  ['Gardener', 'Estate Dealer', 5],
  ['Builder', 'Magnate', 5],
  ['Tycoon', 'Magnate', 5],
  ['Polar Explorer', 'Desert Settler', 5],
  ['Desert Settler', 'Estate Dealer', 5],
  ['Builder', 'Tycoon', 4],
  ['Specialist', 'Energizer', 4],
  ['Mayor', 'Polar Explorer', 4],
  ['Mayor', 'Desert Settler', 4],
  ['Mayor', 'Estate Dealer', 4],
  ['Gardener', 'Polar Explorer', 4],
  ['Gardener', 'Desert Settler', 4],
  ['Ecologist', 'Excentric', 4],
  ['Polar Explorer', 'Landlord', 4],
  ['Mayor', 'Gardener', 3],
  ['Tycoon', 'Excentric', 3],
  ['Polar Explorer', 'Cultivator', 3],
  ['Energizer', 'Thermalist', 3],
  ['Rim Settler', 'Space Baron', 3],
  ['Celebrity', 'Space Baron', 3],
  ['Benefactor', 'Cultivator', 3],
  ['Gardener', 'Benefactor', 2],
  ['Specialist', 'Banker', 2],
  ['Ecologist', 'Tycoon', 2],
  ['Ecologist', 'Diversifier', 2],
  ['Tycoon', 'Scientist', 2],
  ['Tycoon', 'Contractor', 2],
  ['Polar Explorer', 'Estate Dealer', 2],
  ['Rim Settler', 'Celebrity', 2],
  ['Scientist', 'Magnate', 2],
  ['Magnate', 'Space Baron', 2],
  ['Terraformer', 'Cultivator', 2],
  ['Terraformer', 'Gardener', 2],
  ['Builder', 'Miner', 1],
  ['Builder', 'Industrialist', 1],
  ['Planner', 'Scientist', 1],
  ['Generalist', 'Miner', 1],
  ['Specialist', 'Thermalist', 1],
  ['Specialist', 'Miner', 1],
  ['Specialist', 'Industrialist', 1],
  ['Ecologist', 'Cultivator', 1],
  ['Ecologist', 'Magnate', 1],
  ['Tycoon', 'Diversifier', 1],
  ['Tycoon', 'Tactician', 1],
  ['Tycoon', 'Rim Settler', 1],
  ['Tycoon', 'Space Baron', 1],
  ['Diversifier', 'Magnate', 1],
  ['Tactician', 'Scientist', 1],
  ['Tactician', 'Magnate', 1],
  ['Rim Settler', 'Magnate', 1],
  ['Banker', 'Benefactor', 1],
  ['Celebrity', 'Magnate', 1],
  ['Desert Settler', 'Benefactor', 1],
  ['Estate Dealer', 'Benefactor', 1],
  ['Terraformer', 'Landlord', 1],
  ['Terraformer', 'Thermalist', 1],
  ['Terraformer', 'Desert Settler', 1],
  ['Terraformer', 'Estate Dealer', 1],
  ['Gardener', 'Ecologist', 1],

  // Vastitas Borealis
  ['Smith', 'Generalist', 2],
  ['Smith', 'Specialist', 5],
  ['Smith', 'Rim Settler', 3],
  ['Smith', 'Miner', 8],
  ['Smith', 'Industrialist', 5],


  ['Coastguard', 'Mayor', 3],
  ['Coastguard', 'Gardener', 3],
  ['Coastguard', 'Polar Explorer', 3],
  ['Coastguard', 'Landlord', 4],
  ['Coastguard', 'Desert Settler', 5],
  ['Coastguard', 'Estate Dealer', 9],
  ['Coastguard', 'Cultivator', 4],

  ['Forecaster', 'Ecologist', 2],
  ['Forecaster', 'Tactician', 3],
  ['Forecaster', 'Scientist', 5],

  ['Edgedancer', 'Mayor', 2],
  ['Edgedancer', 'Gardener', 4],
  ['Edgedancer', 'Polar Explorer', 5],
  ['Edgedancer', 'Desert Settler', 5],
  ['Edgedancer', 'Estate Dealer', 1],
  ['Edgedancer', 'Cultivator', 4],
  ['Edgedancer', 'Coastguard', 1],

  ['Naturalist', 'Terraformer', 3],
  ['Naturalist', 'Gardener', 2],
  ['Naturalist', 'Generalist', 2],
  ['Naturalist', 'Specialist', 1],
  ['Naturalist', 'Landlord', 4],
  ['Naturalist', 'Thermalist', 6],
  ['Naturalist', 'Desert Settler', 1],
  ['Naturalist', 'Estate Dealer', 1],
  ['Naturalist', 'Benefactor', 5],
  ['Naturalist', 'Cultivator', 3],
  ['Naturalist', 'Edgedancer', 1],

  // Start of fan synergies:
  ['Voyager', 'Rim Settler', 9],

  ['C. Forester', 'Terraformer', 2],
  ['Economizer', 'Terraformer', 2],
  ['Firestarter', 'Terraformer', 1],
  ['Terra Pioneer', 'Terraformer', 1],
  ['Gambler', 'Terraformer', 0.5],
  ['Coastguard', 'Terraformer', 1],
  ['Botanist', 'Terraformer', 2],
  ['Promoter', 'Terraformer', 1],
  ['Edgedancer', 'Terraformer', 1],
  ['Naturalist', 'Terraformer', 3],
  ['Terra Pioneer', 'Mayor', 4],
  ['Gambler', 'Mayor', 0.5],
  ['Coastguard', 'Mayor', 3],
  ['Cosmic Settler', 'Mayor', 5],
  ['Urbanist', 'Mayor', 5],
  ['Edgedancer', 'Mayor', 2],
  ['C. Forester', 'Gardener', 5],
  ['Terra Pioneer', 'Gardener', 4],
  ['Gambler', 'Gardener', 0.5],
  ['Coastguard', 'Gardener', 3],
  ['Botanist', 'Gardener', 5],
  ['Biologist', 'Gardener', 1],
  ['Edgedancer', 'Gardener', 4],
  ['Naturalist', 'Gardener', 2],
  ['T. Collector', 'Builder', 2],
  ['Gambler', 'Builder', 0.5],
  ['Smith', 'Builder', 1],
  ['A. Manufacturer', 'Builder', 1],
  ['Urbanist', 'Builder', 3],
  ['T. Collector', 'Planner', 1],
  ['Gambler', 'Planner', 0.5],
  ['A. Manufacturer', 'Planner', 1],
  ['Visionary', 'Planner', 4],
  ['C. Forester', 'Generalist', 1],
  ['Economizer', 'Generalist', 1],
  ['Gambler', 'Generalist', 0.5],
  ['Smith', 'Generalist', 2],
  ['Botanist', 'Generalist', 1],
  ['Naturalist', 'Generalist', 2],
  ['C. Forester', 'Specialist', 3],
  ['Economizer', 'Specialist', 4],
  ['Gambler', 'Specialist', 0.5],
  ['Smith', 'Specialist', 5],
  ['Capitalist', 'Specialist', 1],
  ['Botanist', 'Specialist', 3],
  ['Naturalist', 'Specialist', 1],
  ['C. Forester', 'Ecologist', 3],
  ['Gambler', 'Ecologist', 0.5],
  ['Botanist', 'Ecologist', 3],
  ['Zoologist', 'Ecologist', 2],
  ['Biologist', 'Ecologist', 9],
  ['Forecaster', 'Ecologist', 2],
  ['Naturalist', 'Ecologist', 1],
  ['Land Specialist', 'Tycoon', 1],
  ['Martian', 'Tycoon', 1],
  ['T. Collector', 'Tycoon', 3],
  ['Spacefarer', 'Tycoon', 2],
  ['Gambler', 'Tycoon', 0.5],
  ['V. Electrician', 'Tycoon', 1],
  ['Botanist', 'Tycoon', 1],
  ['A. Manufacturer', 'Tycoon', 4],
  ['Zoologist', 'Tycoon', 2],
  ['Biologist', 'Tycoon', 1],
  ['Incorporator', 'Tycoon', 2],
  ['Warmonger', 'Tycoon', 1],
  ['Forecaster', 'Tycoon', 1],
  ['Naturalist', 'Tycoon', 1],
  ['Voyager', 'Tycoon', 1],
  ['T. Collector', 'Legend', 5],
  ['Gambler', 'Legend', 0.5],
  ['Promoter', 'Legend', 8],
  ['Warmonger', 'Legend', 2],
  ['T. Collector', 'Diversifier', 1],
  ['Gambler', 'Diversifier', 0.5],
  ['A. Manufacturer', 'Diversifier', 1],
  ['Zoologist', 'Diversifier', 1],
  ['T. Collector', 'Tactician', 1],
  ['Gambler', 'Tactician', 0.5],
  ['A. Manufacturer', 'Tactician', 1],
  ['Forecaster', 'Tactician', 9],
  ['C. Forester', 'Polar Explorer', 1],
  ['Land Specialist', 'Polar Explorer', 4],
  ['Terra Pioneer', 'Polar Explorer', 6],
  ['Gambler', 'Polar Explorer', 0.5],
  ['Coastguard', 'Polar Explorer', 3],
  ['Edgedancer', 'Polar Explorer', 5],
  ['Firestarter', 'Energizer', 2],
  ['Gambler', 'Energizer', 0.5],
  ['V. Electrician', 'Energizer', 8],
  ['Spacefarer', 'Rim Settler', 3],
  ['Gambler', 'Rim Settler', 0.5],
  ['Smith', 'Rim Settler', 3],
  ['Capitalist', 'Rim Settler', 1],
  ['Voyager', 'Rim Settler', 9],
  ['C. Forester', 'Landlord', 1],
  ['Land Specialist', 'Landlord', 4],
  ['Terra Pioneer', 'Landlord', 9],
  ['Coastguard', 'Landlord', 4],
  ['Cosmic Settler', 'Landlord', 3],
  ['Botanist', 'Landlord', 1],
  ['Urbanist', 'Landlord', 4],
  ['Edgedancer', 'Landlord', 4],
  ['Naturalist', 'Landlord', 4],
  ['A. Manufacturer', 'Scientist', 2],
  ['Forecaster', 'Scientist', 5],
  ['Visionary', 'Scientist', 4],
  ['Capitalist', 'Banker', 2],
  ['Incorporator', 'Banker', 1],
  ['Economizer', 'Thermalist', 8],
  ['Firestarter', 'Thermalist', 7],
  ['Naturalist', 'Thermalist', 6],
  ['Spacefarer', 'Miner', 1],
  ['Smith', 'Miner', 8],
  ['Cosmic Settler', 'Miner', 1],
  ['Urbanist', 'Miner', 1],
  ['Capitalist', 'Celebrity', 2],
  ['A. Manufacturer', 'Celebrity', 1],
  ['Spacefarer', 'Industrialist', 1],
  ['V. Electrician', 'Industrialist', 3],
  ['Smith', 'Industrialist', 5],
  ['Urbanist', 'Industrialist', 1],
  ['C. Forester', 'Desert Settler', 1],
  ['Land Specialist', 'Desert Settler', 4],
  ['Terra Pioneer', 'Desert Settler', 6],
  ['Coastguard', 'Desert Settler', 5],
  ['Urbanist', 'Desert Settler', 1],
  ['Edgedancer', 'Desert Settler', 5],
  ['Naturalist', 'Desert Settler', 1],
  ['C. Forester', 'Estate Dealer', 1],
  ['Land Specialist', 'Estate Dealer', 4],
  ['Terra Pioneer', 'Estate Dealer', 6],
  ['Coastguard', 'Estate Dealer', 9],
  ['Urbanist', 'Estate Dealer', 1],
  ['Edgedancer', 'Estate Dealer', 2],
  ['Naturalist', 'Estate Dealer', 1],
  ['C. Forester', 'Benefactor', 3],
  ['Economizer', 'Benefactor', 3],
  ['Firestarter', 'Benefactor', 1],
  ['Botanist', 'Benefactor', 3],
  ['Naturalist', 'Benefactor', 5],
  ['C. Forester', 'Cultivator', 5],
  ['Terra Pioneer', 'Cultivator', 4],
  ['Coastguard', 'Cultivator', 4],
  ['Botanist', 'Cultivator', 5],
  ['Biologist', 'Cultivator', 1],
  ['Edgedancer', 'Cultivator', 4],
  ['Naturalist', 'Cultivator', 3],
  ['Land Specialist', 'Magnate', 1],
  ['Martian', 'Magnate', 1],
  ['T. Collector', 'Magnate', 3],
  ['Spacefarer', 'Magnate', 2],
  ['V. Electrician', 'Magnate', 1],
  ['Botanist', 'Magnate', 1],
  ['Biologist', 'Magnate', 1],
  ['Incorporator', 'Magnate', 2],
  ['Forecaster', 'Magnate', 1],
  ['Naturalist', 'Magnate', 1],
  ['Voyager', 'Magnate', 1],
  ['Spacefarer', 'Space Baron', 9],
  ['Cosmic Settler', 'Space Baron', 5],
  ['Voyager', 'Space Baron', 3],
  ['Zoologist', 'Excentric', 7],
  ['Biologist', 'Excentric', 4],
  ['Smith', 'Contractor', 4],
  ['A. Manufacturer', 'Contractor', 1],
  ['Urbanist', 'Contractor', 3],
  ['Gambler', 'C. Forester', 0.5],
  ['Coastguard', 'C. Forester', 1],
  ['Botanist', 'C. Forester', 9],
  ['Biologist', 'C. Forester', 3],
  ['Forecaster', 'C. Forester', 1],
  ['Naturalist', 'C. Forester', 6],
  ['Firestarter', 'Economizer', 8],
  ['Gambler', 'Economizer', 0.5],
  ['Naturalist', 'Economizer', 8],
  ['Terra Pioneer', 'Land Specialist', 7],
  ['Gambler', 'Land Specialist', 0.5],
  ['Coastguard', 'Land Specialist', 4],
  ['A. Manufacturer', 'Land Specialist', 1],
  ['Edgedancer', 'Land Specialist', 4],
  ['Gambler', 'Martian', 0.5],
  ['A. Manufacturer', 'Martian', 1],
  ['Spacefarer', 'T. Collector', 1],
  ['Gambler', 'T. Collector', 0.5],
  ['V. Electrician', 'T. Collector', 1],
  ['Promoter', 'T. Collector', 1],
  ['A. Manufacturer', 'T. Collector', 4],
  ['Biologist', 'T. Collector', 1],
  ['Forecaster', 'T. Collector', 1],
  ['Gambler', 'Firestarter', 0.5],
  ['V. Electrician', 'Firestarter', 2],
  ['Naturalist', 'Firestarter', 5],
  ['Gambler', 'Terra Pioneer', 0.5],
  ['Coastguard', 'Terra Pioneer', 6],
  ['Edgedancer', 'Terra Pioneer', 8],
  ['Gambler', 'Spacefarer', 0.5],
  ['Smith', 'Spacefarer', 1],
  ['Cosmic Settler', 'Spacefarer', 5],
  ['A. Manufacturer', 'Spacefarer', 2],
  ['Voyager', 'Spacefarer', 3],
  ['V. Electrician', 'Gambler', 0.5],
  ['Smith', 'Gambler', 0.5],
  ['Coastguard', 'Gambler', 0.5],
  ['Capitalist', 'Gambler', 0.5],
  ['A. Manufacturer', 'V. Electrician', 1],
  ['Cosmic Settler', 'Smith', 1],
  ['Urbanist', 'Smith', 2],
  ['Voyager', 'Smith', 3],
  ['Urbanist', 'Coastguard', 1],
  ['Edgedancer', 'Coastguard', 1],
  ['Incorporator', 'Capitalist', 2],
  ['Voyager', 'Capitalist', 1],
  ['Zoologist', 'Botanist', 2],
  ['Biologist', 'Botanist', 5],
  ['Naturalist', 'Botanist', 7],
  ['Warmonger', 'Promoter', 2],
  ['Zoologist', 'A. Manufacturer', 1],
  ['Biologist', 'Zoologist', 6],
  ['Naturalist', 'Zoologist', 2],

];

// This map uses keys of the format "X|Y" where X and Y are MA names. Entries are stored as "X|Y"
// and also "Y|X"; it just makes searching slightly faster. There will also be entries of the type "X|X".
//
// I honestly don't remember why "X|X" is useful, and it's possible it's no longer necessary. That's
// something that should be carefully conisdered and possibly removed', and not just propagated because
// it's what we had to begin with. In other words, someone figure out why, and preserve it, and document
// why, or be certain it's unnecessary and remove this paragraph and the code below that sets "X|X" to 1000.
//
class SynergyMap {
  private readonly map: Map<string, number> = new Map();
  public set(a: string, b: string, weight: number): void {
    this.map.set(a + '|' + b, weight);
    this.map.set(b + '|' + a, weight);
  }

  public get(a: string, b: string) {
    return this.map.get(a + '|' + b) || 0;
  }
}

export const synergies: SynergyMap = new SynergyMap();

for (const [a, b, weight] of synergiesData) {
  synergies.set(a, b, weight);
}
